vich_uploader:
    db_driver: orm
    mappings:
        realisation_images:
            uri_prefix:  /upload_runtime/realisation
            upload_destination: '%kernel.project_dir%/public/upload_runtime/realisation'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            delete_on_remove: true  # Active la suppression automatique
            delete_on_update: true